name: "Download scia_tool"
inputs:
  name :
    description: "The name of tool to download"
    required: true

  token:
    description: "Token to access ecode github"
    required: true

runs:
  using: "composite"
  steps:
    - name: Download tool
      shell: bash
      run : |
        set -euo pipefail
        git clone -b v1.0.0 https://${{ inputs.token }}@github.ecodesamsung.com/CRTM/scia_tool
        cd scia_tool/${{ inputs.name }} && git lfs pull --include ${{ inputs.name }} 

    - name: Verify tool
      shell: bash
      run : |
        if [[ "${{ inputs.name }}" == "generator" ]]; then
          EXPECTED_HASH="09ff934714d0b8ff1f39d7e64a975f0bb88718cbcb2395425b35fc606f4f73d8"
        elif [[ "${{ inputs.name }}" == "verifier" ]]; then
          EXPECTED_HASH="ebd660a4e34060db3259cb2408434bf20f459e6b8e3bbb050424d108b5317454"
        fi
        COMPUTED_HASH=$(sha256sum scia_tool/${{ inputs.name }}/${{ inputs.name }} | awk '{print $1}')
        set -euo pipefail
        echo "${{ inputs.name }} expected hash is $EXPECTED_HASH"
        echo "${{ inputs.name }} computed hash is $COMPUTED_HASH"
        if [[ "$COMPUTED_HASH" != "$EXPECTED_HASH" ]]; then
            echo "${{ inputs.name }} hash do not match"
            exit -2
        fi

    - name: Build tool contaniner
      shell: bash
      env :
        GITHUB_CONTEXT: "${{ toJSON(github) }}"
      run : |
        set -euo pipefail
        docker build --build-arg GITHUB_CONTEXT="${GITHUB_CONTEXT}" -t scia:${{ inputs.name }} scia_tool/${{ inputs.name }}
        rm -rf scia_tool

