name: Releasor for Python Project

on:
  workflow_call:
    inputs:
      version:
        description: "python version"
        required: true
        type: string

    secrets:
      EXPECTED_REPOSITORY:
        required: true
      ECODETOKEN:
        required: true
      GITHUBTOKEN:
        required: true

    outputs:
      artifact:
         description: "Artifacts of the Builder"
         value: ${{ jobs.Builder.outputs.artifact }}
      hash:
         description: "Hash of the Artifacts"
         value: ${{ jobs.Builder.outputs.hash }}

jobs:
  Builder:
    uses: samsung/supplychainassurance/.github/workflows/python_builder.yml@seperate-builder
    with:
      version: "${{ inputs.version }}"
      upload: true

  SLSA_Release:
    needs: [ Builder ]
    permissions:
      id-token: write
      contents: write
    uses: samsung/supplychainassurance/.github/workflows/slsa_release.yml@seperate-builder
    with:
      hash: "${{ needs.Builder.outputs.hash }}"
      artifact: "${{ needs.Builder.outputs.artifact }}"
      build_cmd: "${{ needs.Builder.outputs.build_command }}"

    secrets:
      EXPECTED_REPOSITORY: "${{ secrets.EXPECTED_REPOSITORY }}"
      ECODETOKEN: "${{ secrets.ECODETOKEN }}"

  Upload_Asset:
    needs: [ Builder, SLSA_Release ]
    runs-on: ubuntu-latest
    steps:
    - name: Upload Release Asset
      uses: samsung/supplychainassurance/.github/actions/upload-release-asset@v1.0.1
      env:
        GITHUBTOKEN: ${{ secrets.GITHUBTOKEN }}
      with:
        artifacts: ${{ needs.SLSA_Release.outputs.artifacts }}
